### ISSUE TITLE
Upgrade user experience

### ISSUE THREAD

**Issue by invisibleroads** [crosscompute/jupyterlab-crosscompute#5]
# Phase 0
- [x] Check that console.log shows for each server sent event

# Phase 1
- [x] Append server sent event message to end of text for log dialog window

# Phase 2
- [x] Wait for payload in event message
- [x] Trigger download loop (maybe via jupyterlab signals) if payload is in event message

# Phase 3
- [x] Change Close to Cancel
- [x] Make tracebacks easier to read by using separate divs for each event

# Phase 4
- [x] Make sure tracebacks are easy to read
- [Cancelled] Make dialog modal -- don't disappear on click
- [Cancelled] Rename Cancel to Close when process is done

# Phase 5
- [x] Show progress bar based on index / count
- [x] Consider chronological order
- [ ] Scroll to bottom

# Phase X
- [ ] Let user work while print is being generated
- [ ] Change dialog into a panel
- [ ] Continue running automation until user cancels automation or closes panel
- [ ] Save download in ~/Downloads/TIMESTAMP.zip
